---
# File Name: template-config.yaml
# Created By: ZW
# Created On: 2022-07-07
# Purpose: Template configuration for the ATAC-Seq pipeline
---
DOC_TYPE: "GLOBAL_CONFIG"
analysis_name: 'ATAC-Seq-pipeline'
working_directory: '`pwd`'
files: {
  reference_fasta: "/path/to/genome/reference.fa.gz"

  sequencing: []
}
---
DOC_TYPE: "RULE_CONFIG" 
rule_name: "BWA_Index_Reference",
resources: {
  walltime: "02:30:00",
  nodes: 1,
  cpus_per_node: 4,
  total_memory_mb: 8000
}
parameters: {
  index_files: ["reference.amb", "reference.ann",
    "reference.bwt", "reference.pac", "reference.sa"
  ]
}
---
