---
# File Name: template-config.yaml
# Created By: ZW
# Created On: 2022-07-07
# Purpose: Template configuration for the BOLT-LMM GWAS pipeline

analysis_name: 'LV-ATAC-Seq'
working_directory: '`pwd`'
files:
 - {"run": "run_A",
    "fq1": "readsA-1.fastq.gz",
    "fq2": "readsB-2.fastq.gz",
    "annos": {"cell_type": 'ctA'}
 }
 - {"run": "run_B",
    "fq1": "readsB-1.fastq.gz",
    "fq2": "readsB-2.fastq.gz",
    "annos": {"cell_type": 'ctB'}
 }
