---
# File Name: template-config.yaml
# Created By: ZW
# Created On: 2022-07-07
# Purpose: Template configuration for the ATAC-Seq pipeline
---
DOC_TYPE: "configuration"
GLOBAL_CONFIG:
  analysis_name: 'LV-ATAC-Seq'
  working_directory: '`pwd`'
RULE_CONFIG: [
  {
    rule_name: "BWA_Index_Reference",
    resources: {
      walltime: "02:30:00",
      nodes: 1,
      processors_per_node: 4,
      total_memory: 8000
    }
  }
]
---
DOC_TYPE: "file_meta"
reference_fasta: "mygenomeversion.fasta"
reference_fasta_index: "myindexdir/"
files: [
  {
      run: "run_A",
      fq1: "readsA-1.fastq.gz",
      fq2: "readsB-2.fastq.gz",
      annos: {cell_type: "ctA"}
    },
  {
      run: "run_A",
      fq1: "readsA-1.fastq.gz",
      fq2: "readsB-2.fastq.gz",
      annos: {
        cell_type: "ctA"
      }
    }
]